# Config file for github.com/alpkeskin/mosint
# For default usage just rename this file to .mosint.yaml and put it in your home directory

services:
  breach_directory_api_key: ""
  emailrep_api_key: ""
  hunter_api_key: "" 
  intelx_api_key: ""
  haveibeenpwned_api_key: ""

settings:
  intelx_max_results: 20
  intelx_host: "https://free.intelx.io" # or https://api.intelx.io